export default function TermsConditions() {
  return (
    <div className="pt-32 pb-20 container mx-auto px-4 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
      <div className="prose prose-slate max-w-none space-y-6 text-slate-600">
        <p>Last Updated: May 2026</p>
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
          <p>By accessing and using ResumeTool, you accept and agree to be bound by the terms and provision of this agreement.</p>
        </section>
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Use License</h2>
          <p>Permission is granted to use the generated summaries for your personal resume and job applications. You may not use this tool for mass commercial generation or scraping.</p>
        </section>
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Disclaimer</h2>
          <p>The summaries generated by our AI are suggestions. ResumeTool does not guarantee employment or the accuracy of the AI-generated text. It is the user's responsibility to review and verify all content before use.</p>
        </section>
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Limitation of Liability</h2>
          <p>ResumeTool shall not be held liable for any damages arising out of the use or inability to use the tools provided on this website.</p>
        </section>
      </div>
    </div>
  );
}
